### ISSUE TITLE
Use built in React Navigation, Bottom Tab Navigator

### ISSUE THREAD

**Issue by Zakpak0** [christoph-codes/soundup#64]
Problem: If i click the news tab and click into a news article, then it moves to the watch tab.
**Expected: Stay on the news tab if the user enters a news article**

_Originally posted by @christoph-codes in https://github.com/christoph-codes/soundup/issues/60#issuecomment-1614966108_

**Comment by Zakpak0** [comment]
#

**Comment by Zakpak0** [comment]
Will use the built in Tab Navigator to solve this issue.

**Comment by Zakpak0** [comment]
@christoph-codes Hey Chirstoph, there's a lot of overhead to get the app running on the development side. For now I'll write the code how I believe it should be without running it.
And maybe we can connect on that part.

**Comment by Zakpak0** [comment]
#65 contains a PR with the implementation.
Let me know if it runs and any issues you're having with it.
I couldn't verify it runs on my end because of authentication issues etc

**Comment by christoph-codes** [comment]
This was closed with the latest PR #66. Resolves #60 .
Thanks @Zakpak0 !
